/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebarLayout/route'
import { Route as IndexImport } from './routes/index'
import { Route as SidebarLayoutAboutImport } from './routes/_sidebarLayout/about'

// Create/Update Routes

const SidebarLayoutRouteRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SidebarLayoutAboutRoute = SidebarLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_sidebarLayout': {
      id: '/_sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_sidebarLayout/about': {
      id: '/_sidebarLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SidebarLayoutAboutImport
      parentRoute: typeof SidebarLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface SidebarLayoutRouteRouteChildren {
  SidebarLayoutAboutRoute: typeof SidebarLayoutAboutRoute
}

const SidebarLayoutRouteRouteChildren: SidebarLayoutRouteRouteChildren = {
  SidebarLayoutAboutRoute: SidebarLayoutAboutRoute,
}

const SidebarLayoutRouteRouteWithChildren =
  SidebarLayoutRouteRoute._addFileChildren(SidebarLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof SidebarLayoutRouteRouteWithChildren
  '/about': typeof SidebarLayoutAboutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof SidebarLayoutRouteRouteWithChildren
  '/about': typeof SidebarLayoutAboutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_sidebarLayout': typeof SidebarLayoutRouteRouteWithChildren
  '/_sidebarLayout/about': typeof SidebarLayoutAboutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about'
  id: '__root__' | '/' | '/_sidebarLayout' | '/_sidebarLayout/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarLayoutRouteRoute: typeof SidebarLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarLayoutRouteRoute: SidebarLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_sidebarLayout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_sidebarLayout": {
      "filePath": "_sidebarLayout/route.tsx",
      "children": [
        "/_sidebarLayout/about"
      ]
    },
    "/_sidebarLayout/about": {
      "filePath": "_sidebarLayout/about.tsx",
      "parent": "/_sidebarLayout"
    }
  }
}
ROUTE_MANIFEST_END */
