/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebarLayout/route'
import { Route as SidebarLayoutHomeImport } from './routes/_sidebarLayout/home'
import { Route as SidebarLayoutAboutImport } from './routes/_sidebarLayout/about'

// Create/Update Routes

const SidebarLayoutRouteRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebarLayout',
  getParentRoute: () => rootRoute,
} as any)

const SidebarLayoutHomeRoute = SidebarLayoutHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)

const SidebarLayoutAboutRoute = SidebarLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SidebarLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebarLayout': {
      id: '/_sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_sidebarLayout/about': {
      id: '/_sidebarLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SidebarLayoutAboutImport
      parentRoute: typeof SidebarLayoutRouteImport
    }
    '/_sidebarLayout/home': {
      id: '/_sidebarLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SidebarLayoutHomeImport
      parentRoute: typeof SidebarLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface SidebarLayoutRouteRouteChildren {
  SidebarLayoutAboutRoute: typeof SidebarLayoutAboutRoute
  SidebarLayoutHomeRoute: typeof SidebarLayoutHomeRoute
}

const SidebarLayoutRouteRouteChildren: SidebarLayoutRouteRouteChildren = {
  SidebarLayoutAboutRoute: SidebarLayoutAboutRoute,
  SidebarLayoutHomeRoute: SidebarLayoutHomeRoute,
}

const SidebarLayoutRouteRouteWithChildren =
  SidebarLayoutRouteRoute._addFileChildren(SidebarLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof SidebarLayoutRouteRouteWithChildren
  '/about': typeof SidebarLayoutAboutRoute
  '/home': typeof SidebarLayoutHomeRoute
}

export interface FileRoutesByTo {
  '': typeof SidebarLayoutRouteRouteWithChildren
  '/about': typeof SidebarLayoutAboutRoute
  '/home': typeof SidebarLayoutHomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_sidebarLayout': typeof SidebarLayoutRouteRouteWithChildren
  '/_sidebarLayout/about': typeof SidebarLayoutAboutRoute
  '/_sidebarLayout/home': typeof SidebarLayoutHomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/home'
  id:
    | '__root__'
    | '/_sidebarLayout'
    | '/_sidebarLayout/about'
    | '/_sidebarLayout/home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SidebarLayoutRouteRoute: typeof SidebarLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRouteRoute: SidebarLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_sidebarLayout"
      ]
    },
    "/_sidebarLayout": {
      "filePath": "_sidebarLayout/route.tsx",
      "children": [
        "/_sidebarLayout/about",
        "/_sidebarLayout/home"
      ]
    },
    "/_sidebarLayout/about": {
      "filePath": "_sidebarLayout/about.tsx",
      "parent": "/_sidebarLayout"
    },
    "/_sidebarLayout/home": {
      "filePath": "_sidebarLayout/home.tsx",
      "parent": "/_sidebarLayout"
    }
  }
}
ROUTE_MANIFEST_END */
